language: python
python:
    - 2.7
    - 3.5
    - 3.6
    
install:
    - pip install -r requirements.travis.txt
    - pip install pytest-cov
    - pip install coveralls
    - pip install .

script:
    - pytest
    - pytest --cov=skycalc_ipy/
    - pytest --doctest-modules

after_success:
    - coveralls
